# Generated by Django 5.0.3 on 2024-04-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0004_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('eapp.product',),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=False, max_digits=7),
        ),
    ]
